robot_nagivation::GameModel
ProgramData robot_nagivation.GameModel._data
Referenced by robot_nagivation.GameModel.GameModel, robot_nagivation.GameModel.MoveAgent, robot_nagivation.GameModel.Run, robot_nagivation.GameModel.WithinMap.
robot_nagivation.GameModel.GameModel(ref ProgramData data)
References robot_nagivation.GameModel._data.
void robot_nagivation.GameModel.Initialise()
References robot_nagivation.GameModel.CreatePercepts.
bool robot_nagivation.GameModel.WithinMap(Vector2i pos)
References robot_nagivation.GameModel._data, robot_nagivation.ProgramData.Map, robot_nagivation.Map.MapMatrix.
Referenced by robot_nagivation.GameModel.MoveAgent.
void robot_nagivation.GameModel.MoveAgent(AgentActions direction)
References robot_nagivation.GameModel._data, robot_nagivation.Map.AgentPos, robot_nagivation.ProgramData.Map, robot_nagivation.GameModel.WithinMap.
Referenced by robot_nagivation.GameModel.Run.
Percepts robot_nagivation.GameModel.CreatePercepts()
Referenced by robot_nagivation.GameModel.Initialise, robot_nagivation.GameModel.Run.
void robot_nagivation.GameModel.Run()
References robot_nagivation.GameModel._data, robot_nagivation.GameModel.CreatePercepts, robot_nagivation.ProgramData.Finished, robot_nagivation.GameModel.MoveAgent.