robot_nagivation::Agent
AgentData robot_nagivation.Agent._agentData
Referenced by robot_nagivation.Agent.Initialise.
AgentState robot_nagivation.Agent._state
Referenced by robot_nagivation.Agent.Initialise, robot_nagivation.Agent.IsFinished.
string robot_nagivation.Agent._name
int robot_nagivation.Agent._agentDelay
AgentData robot_nagivation.Agent.AgentData
Referenced by robot_nagivation.SFMLView.Draw, robot_nagivation.SFMLView.DrawNodeDisplay, robot_nagivation.Agent.Initialise.
AgentState robot_nagivation.Agent.State
Referenced by robot_nagivation.GreedyFirstAgent.next, robot_nagivation.UniformCostAgent.next, robot_nagivation.IterativeDDFSAgent.next, robot_nagivation.DepthFirstAgent.next, robot_nagivation.BreadthFirstAgent.next.
int robot_nagivation.Agent.AgentDelay
Referenced by robot_nagivation.GreedyFirstAgent.next, robot_nagivation.UniformCostAgent.next, robot_nagivation.IterativeDDFSAgent.next, robot_nagivation.DepthFirstAgent.next, robot_nagivation.BreadthFirstAgent.next.
string robot_nagivation.Agent.Name
Referenced by robot_nagivation.SFMLView.DrawNodeDisplay, robot_nagivation.AStarAgent.Initialise, robot_nagivation.DijkstraAgent.Initialise, robot_nagivation.GreedyFirstAgent.Initialise, robot_nagivation.RandomAgent.Initialise, robot_nagivation.UniformCostAgent.Initialise, robot_nagivation.IterativeDDFSAgent.Initialise, robot_nagivation.DepthFirstAgent.Initialise, robot_nagivation.BreadthFirstAgent.Initialise.
virtual void robot_nagivation.Agent.Initialise(Percepts percepts)
References robot_nagivation.Agent._agentData, robot_nagivation.Agent._state, robot_nagivation.Agent.AgentData.
abstract AgentActions robot_nagivation.Agent.next(Percepts percepts)
virtual void robot_nagivation.Agent.UpdateInternalHeap(Queue< Node< TileType >> list)
Referenced by robot_nagivation.GreedyFirstAgent.next, robot_nagivation.IterativeDDFSAgent.next, robot_nagivation.DepthFirstAgent.next, robot_nagivation.BreadthFirstAgent.next.
virtual void robot_nagivation.Agent.UpdateInternalHeap(Stack< Node< TileType >> list)
virtual void robot_nagivation.Agent.UpdateInternalHeap(List< Node< TileType >> list)
virtual int robot_nagivation.Agent.HeuristicFunction(Vector2i Pos, Percepts percepts)
Referenced by robot_nagivation.Agent.SearchSurroundingNodes.
virtual int robot_nagivation.Agent.CostFunction(Vector2i Pos, Percepts percepts)
Referenced by robot_nagivation.Agent.SearchSurroundingNodes.
virtual bool robot_nagivation.Agent.IsGoalNode(Node< TileType > node)
Referenced by robot_nagivation.GreedyFirstAgent.next, robot_nagivation.UniformCostAgent.next, robot_nagivation.IterativeDDFSAgent.next, robot_nagivation.DepthFirstAgent.next, robot_nagivation.BreadthFirstAgent.next.
virtual bool robot_nagivation.Agent.IsFinished()
References robot_nagivation.Agent._state.
Queue<AgentActions> robot_nagivation.Agent.DetermineMoveSet()
Referenced by robot_nagivation.GreedyFirstAgent.next, robot_nagivation.UniformCostAgent.next, robot_nagivation.IterativeDDFSAgent.next, robot_nagivation.DepthFirstAgent.next, robot_nagivation.BreadthFirstAgent.next.
List<Node<TileType> > robot_nagivation.Agent.DetermineAgentPath(Node< TileType > start, Node< TileType > end)
Referenced by robot_nagivation.GreedyFirstAgent.next, robot_nagivation.UniformCostAgent.next, robot_nagivation.IterativeDDFSAgent.next, robot_nagivation.DepthFirstAgent.next, robot_nagivation.BreadthFirstAgent.next.
virtual bool robot_nagivation.Agent.WithinMap(Vector2i pos, Percepts percepts)
References robot_nagivation.Percepts.MapMatrix.
Referenced by robot_nagivation.Agent.SearchSurroundingNodes.
virtual List<Node<TileType> > robot_nagivation.Agent.SearchSurroundingNodes(Node< TileType > currentNode, Percepts percepts)
References robot_nagivation.Agent.CostFunction, robot_nagivation.AgentData.DirectionalMovementCost, robot_nagivation.Agent.HeuristicFunction, robot_nagivation.AgentData.SearchedPos, robot_nagivation.Agent.WithinMap.
Referenced by robot_nagivation.GreedyFirstAgent.next, robot_nagivation.UniformCostAgent.next, robot_nagivation.IterativeDDFSAgent.next, robot_nagivation.DepthFirstAgent.next, robot_nagivation.BreadthFirstAgent.next.