robot_nagivation::SFMLView
ProgramData robot_nagivation.SFMLView._data
Referenced by robot_nagivation.SFMLView.Close, robot_nagivation.SFMLView.Draw, robot_nagivation.SFMLView.DrawNodeDisplay, robot_nagivation.SFMLView.SFMLView.
RenderWindow robot_nagivation.SFMLView._window
Referenced by robot_nagivation.SFMLView.SFMLView, robot_nagivation.SFMLView.TakeScreenshotOfWindows.
RenderWindow robot_nagivation.SFMLView._nodeWindow
Referenced by robot_nagivation.SFMLView.SFMLView, robot_nagivation.SFMLView.TakeScreenshotOfWindows.
View robot_nagivation.SFMLView._nodeView
Referenced by robot_nagivation.SFMLView.Draw, robot_nagivation.SFMLView.SFMLView.
float robot_nagivation.SFMLView._nodeViewPos
Referenced by robot_nagivation.SFMLView.Draw, robot_nagivation.SFMLView.SFMLView, robot_nagivation.SFMLView.Window_MouseWheeled.
Font robot_nagivation.SFMLView._font
Referenced by robot_nagivation.SFMLView.Draw, robot_nagivation.SFMLView.DrawBackground, robot_nagivation.SFMLView.DrawNodeDisplay, robot_nagivation.SFMLView.SFMLView.
Vector2i robot_nagivation.SFMLView._windowSize
Referenced by robot_nagivation.SFMLView.SetWindowSize.
robot_nagivation.SFMLView.SFMLView(ref ProgramData data)
References robot_nagivation.SFMLView._data, robot_nagivation.SFMLView._font, robot_nagivation.SFMLView._nodeView, robot_nagivation.SFMLView._nodeViewPos, robot_nagivation.SFMLView._nodeWindow, robot_nagivation.SFMLView._window, robot_nagivation.SFMLView.Window_KeyPressed, robot_nagivation.SFMLView.Window_MouseWheeled.
void robot_nagivation.SFMLView.TakeScreenshot(ref RenderWindow window, string fileName)
Referenced by robot_nagivation.SFMLView.TakeScreenshotOfWindows.
void robot_nagivation.SFMLView.TakeScreenshotOfWindows(string fileName)
References robot_nagivation.SFMLView._nodeWindow, robot_nagivation.SFMLView._window, robot_nagivation.SFMLView.TakeScreenshot.
Referenced by robot_nagivation.SFMLView.Close.
void robot_nagivation.SFMLView.SetWindowSize(int width, int height)
References robot_nagivation.SFMLView._windowSize.
Color robot_nagivation.SFMLView.HashedPosColor(int x, int y, int seed)
Referenced by robot_nagivation.SFMLView.Draw, robot_nagivation.SFMLView.DrawNodeDisplay.
void robot_nagivation.SFMLView.DrawNodeDisplay()
References robot_nagivation.SFMLView._data, robot_nagivation.SFMLView._font, robot_nagivation.ProgramData.Agent, robot_nagivation.Agent.AgentData, robot_nagivation.SFMLView.HashedPosColor, robot_nagivation.AgentData.InternalHeap, robot_nagivation.Agent.Name, robot_nagivation.AgentData.PosToSearch, robot_nagivation.AgentData.RootNode.
Referenced by robot_nagivation.SFMLView.Draw.
void robot_nagivation.SFMLView.Draw()
References robot_nagivation.SFMLView._data, robot_nagivation.SFMLView._font, robot_nagivation.SFMLView._nodeView, robot_nagivation.SFMLView._nodeViewPos, robot_nagivation.ProgramData.Agent, robot_nagivation.Agent.AgentData, robot_nagivation.ProgramData.AgentDecisions, robot_nagivation.Map.AgentPos, robot_nagivation.SFMLView.DrawBackground, robot_nagivation.SFMLView.DrawNodeDisplay, robot_nagivation.SFMLView.HashedPosColor, robot_nagivation.ProgramData.Map, robot_nagivation.Map.MapMatrix, robot_nagivation.AgentData.Path, robot_nagivation.AgentData.PosToSearch, robot_nagivation.AgentData.SearchedNodes.
void robot_nagivation.SFMLView.Close()
References robot_nagivation.SFMLView._data, robot_nagivation.ProgramData.DisplayMode, robot_nagivation.ProgramData.OutputName, robot_nagivation.SFMLView.TakeScreenshotOfWindows.
void robot_nagivation.SFMLView.DrawBackground()
References robot_nagivation.SFMLView._font.
Referenced by robot_nagivation.SFMLView.Draw.
void robot_nagivation.SFMLView.Window_KeyPressed(object sender, SFML.Window.KeyEventArgs e)
Referenced by robot_nagivation.SFMLView.SFMLView.
void robot_nagivation.SFMLView.Window_MouseWheeled(object sender, SFML.Window.MouseWheelScrollEventArgs e)
References robot_nagivation.SFMLView._nodeViewPos.
Referenced by robot_nagivation.SFMLView.SFMLView.